### ISSUE TITLE
JSON Formatting Options ?

### ISSUE THREAD

**Issue by Compr0mzd** [Matmaus/LnkParse3#19]
Would it be possible instead of printing the json to stdout to make a usable json object ?

**Comment by Matmaus** [comment]
Hi, thanks for the question. You can use method `get_json()` instead of `print_json()`. See example below:
```python
>>> import LnkParse3
>>> with open('tests/samples/microsoft_example', 'rb') as indata:
>>>    lnk = LnkParse3.lnk_file(indata)
>>>    json_repr = lnk.get_json()
>>>    json_repr['link_info']['location_info']['drive_type']
'DRIVE_FIXED'
>>>
```
Is it what you were thinking about?



I see it could be useful to create API documentation :slightly_smiling_face:

**Comment by Compr0mzd** [comment]
> Hi, thanks for the question. You can use method `get_json()` instead of `print_json()`. See example below:
> 
> ```python
> >>> import LnkParse3
> >>> with open('tests/samples/microsoft_example', 'rb') as indata:
> >>>    lnk = LnkParse3.lnk_file(indata)
> >>>    json_repr = lnk.get_json()
> >>>    json_repr['link_info']['location_info']['drive_type']
> 'DRIVE_FIXED'
> >>>
> ```
> 
> Is it what you were thinking about?
> 
> I see it could be useful to create API documentation 🙂

Hey I appreciate the fast reply. Indeed I found the get_json() function afterwards and was doing some testings. I'm trying to do bulk parsing on a lot of lnk files. It seems there is some json formatting issues when i try to send them to a splunk server

**Comment by Matmaus** [comment]
> It seems there is some json formatting issues when i try to send them to a splunk server

Would it be possible to provide some file(s) with issues? I can look what is the problem.
