### ISSUE TITLE
Extraction of SID

### ISSUE THREAD

**Issue by dspruell-i01** [Matmaus/LnkParse3#23]
LNK files can store the SID of the creating user account in the file. It seems that this may not currently be extracted. Is it possible to add support for extracting this artifact?

Sample LNK files:

- 02eccb041972825d51b71e88450b094cf692b9f5f46f5101ab3f2210e2e1fe71
- 20ad6fa72982a6ba0f9499361b2aa3a3f5cca73fd397c2969d08a4c5f2866814
- 24ee20d7f254e1e327ecd755848b8b72cd5e6273cf434c3a520f780d5a098ac9
- 2cea2a1f53dac3f4fff156eacc2ecc8e98b1a64f0f5b5ee1c42c69d9a226c55c
- 32febef64410a6fcff07a6f95f51c25506c291ef13bdaa0937e2b9ce08d2d406
- 59d74f7e172a2ee14e5e43b9704ac95428b28741f1dbadbf5c9279dd37a11f86
- 61669c7e59036ae95a2886cf5a42a89633ff8c53cf75e7cb89e0be9f6d4030f4
- 65c40ca3e96786d292bb9c60f2e0b31641a23c129f2af0bbf5622d33186be6e3
- 70b6961af57bce72b89103197c8897a4ae3ce5fdb835ccd050f24acbac52900d
- 843ab931b2bf9ac5cbe5b08189349b440ee586de655130567ab95ae9c86aa2ab
- b0d7118d75c0f2a99fa5b319148b89148800e5db06ee403d6a31c451a8a54f2b
- d627688bb5c853df92555cc3c595cc210d83809f3357e0cbccb478c778712967

**Comment by Matmaus** [comment]
I think the support was added recently, but it is only in `master` branch yet. I can make a new release this weekend.

Below is SID parsed from `02eccb041972825d51b71e88450b094cf692b9f5f46f5101ab3f2210e2e1fe71`. Can you please verify it?
```
S-1-5-21-1499925678-132529631-3571256938-1001
```

**Comment by dspruell-i01** [comment]
> I think the support was added recently, but it is only in `master` branch yet. I can make a new release this weekend.
> 
> Below is SID parsed from `02eccb041972825d51b71e88450b094cf692b9f5f46f5101ab3f2210e2e1fe71`. Can you please verify it?
> 
> ```
> S-1-5-21-1499925678-132529631-3571256938-1001
> ```

Affirmative, that's what I expected to see for that sample. Nice!

**Comment by Matmaus** [comment]
A new version `v1.3.0` with support to extract (not only) SID has been released.
